### PR TITLE
Update Java to 8u131

### PR DESCRIPTION
**Pull request by cawallin**

### CODE REVIEW

**Comment by alandpost** [comment]
Looks good to me!

**Review by alandpost — APPROVED** [review]
Great!

**Review by arhimondr — APPROVED** [review]

**Comment by losipiuk** [comment]
The JDK link `http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.rpm` no longer works. At least when I put it in the browser. Is that expected?

AFAIK after recent changes made by oracle the URLs to specific JDK versions are short-lived and cannot be used in scripts like that.

**Comment by cawallin** [comment]
In order to use that link, you need to add a header that accepts the Oracle license. I verified that it works.

Also that's right about the changes by Oracle. I checked with Jack and currently they don't have a better solution than just using the most recent download URL; we'll have to be diligent about updating it.

**Comment by ebd2** [comment]
> Also that's right about the changes by Oracle. I checked with Jack and currently they don't have a better solution than just using the most recent download URL; we'll have to be diligent about updating it.

Gotta love Oracle...

**Pull request merged**
